export const en = {
  "Crop":"قص",
  "3:2":'3:2',
  "4:3":'4:3',
  "5:4":'5:4',
  "7:5":'7:5',
  "16:9":'16:9',
  "Apply":"تطبيق",
  "Arrow":"سهم",
  "Arrow-2":"سهم 2",
  "Arrow-3":"سهم 3 ",
  "Blend":"مزج",
  "Blur":"",
  "Bold":"",
  "Brightness":"",
  "Bubble":"",
  "Cancel":"",
  "Center":"",
  "Circle":"",
  "Color":"",
  "Color-Filter" : "",
  "Custom":"",
  "Custom icon":"",
  "Delete":"",
  "Delete-all":"",
  "Distance":"",
  "Download":"",
  "Draw":"",
  "Emboss":"",
  "Fill":"",
  "Filter":"",
  "Flip":"",
  "Flip X":"",
  "Flip Y":"",
  "Free":"",
  "Grayscale":"",
  "Heart":"",
  "Icon":"",
  "Invert":"",
  "Italic":"",
  "Left":"",
  "Load":"",
  "Load Mask Image":"",
  "Location":"",
  "Mask":"",
  "Multiply":"",
  "Noise":"",
  "Pixelate":"",
  "Polygon":"",
  "Range":"",
  "Rectangle":"",
  "Redo":"",
  "Remove White":"",
  "Reset":"",
  "Right":"",
  "Rotate":"",
  "Sepia":"",
  "Sepia2":"",
  "Shape":"",
  "Sharpen":"",
  "Square":"",
  "Star-1":"",
  "Star-2":"",
  "Straight":"",
  "Stroke":"",
  "Text":"",
  "Text size":"",
  "Threshold":"",
  "Tint":"",
  "Triangle":"",
  "Underline":"",
  "Undo":"",
  "Value":""
}
// export const en = {
//   'tui-image-editor-menus-buttons-crop-tooltip': 'قص',
//   'tui-image-editor-menus-buttons-delete': 'مسح',
//   'tui-image-editor-menus-buttons-deleteAll': 'مسح الكل',
//   'tui-image-editor-menus-buttons-download': 'تنزيل',
//   'tui-image-editor-menus-buttons-drag': 'سحب',
//   'tui-image-editor-menus-buttons-draw': 'رسم',
//   'tui-image-editor-menus-buttons-filter': 'فلتر',
//   'tui-image-editor-menus-buttons-flip': 'قلب',
//   'tui-image-editor-menus-buttons-history': 'التاريخ',
//   'tui-image-editor-menus-buttons-icon': 'ايقونات',
//   'tui-image-editor-menus-buttons-load': 'تحميل',
//   'tui-image-editor-menus-buttons-mask': 'Mask',
//   'tui-image-editor-menus-buttons-redo': 'إعادة',
//   'tui-image-editor-menus-buttons-reset': 'إعادة تعيين',
//   'tui-image-editor-menus-buttons-rotate': 'تدوير',
//   'tui-image-editor-menus-buttons-shape': 'شكل',
//   'tui-image-editor-menus-buttons-text': 'نص',
//   'tui-image-editor-menus-buttons-undo': 'تراجع',
//   'tui-image-editor-menus-buttons-zoomIn': 'تكبير',
//   'tui-image-editor-menus-buttons-zoomOut': 'تصغير',

//   'tui-image-editor-submenus-crop-custom': 'Custom',
//   'tui-image-editor-submenus-crop-square': 'Square',
//   'tui-image-editor-submenus-crop-apply': 'Apply',
//   'tui-image-editor-submenus-crop-cancel': 'Cancel',
//   'tui-image-editor-submenus-flip-x': 'Flip X',
//   'tui-image-editor-submenus-flip-y': 'Flip Y',
//   'tui-image-editor-submenus-flip-reset': 'Reset',
//   'tui-image-editor-submenus-rotate-slider': 'Rotation',
//   'tui-image-editor-submenus-draw-free': 'Free',
//   'tui-image-editor-submenus-draw-straight': 'Straight',
//   'tui-image-editor-submenus-draw-color': 'Color',
//   'tui-image-editor-submenus-draw-strokeWidth': 'Stroke width',
//   'tui-image-editor-submenus-shape-rectangle': 'Rectangle',
//   'tui-image-editor-submenus-shape-circle': 'Circle',
//   'tui-image-editor-submenus-shape-triangle': 'Triangle',
//   'tui-image-editor-submenus-shape-fill': 'Fill',
//   'tui-image-editor-submenus-shape-stroke': 'Stroke',
//   'tui-image-editor-submenus-shape-strokeWidth': 'Stroke width',
//   'tui-image-editor-submenus-icon-arrow1': 'Arrow-1',
//   'tui-image-editor-submenus-icon-arrow2': 'Arrow-2',
//   'tui-image-editor-submenus-icon-arrow3': 'Arrow-3',
//   'tui-image-editor-submenus-icon-star1': 'Star-1',
//   'tui-image-editor-submenus-icon-star2': 'Star-2',
//   'tui-image-editor-submenus-icon-polygon': 'Polygon',
//   'tui-image-editor-submenus-icon-location': 'Location',
//   'tui-image-editor-submenus-icon-heart': 'Heart',
//   'tui-image-editor-submenus-icon-bubble': 'Bubble',
//   'tui-image-editor-submenus-icon-customIcon': 'Custom icon',
//   'tui-image-editor-submenus-icon-color': 'Color',
//   'tui-image-editor-submenus-text-bold': 'Bold',
//   'tui-image-editor-submenus-text-italic': 'Italic',
//   'tui-image-editor-submenus-text-underline': 'Underline',
//   'tui-image-editor-submenus-text-left': 'Left',
//   'tui-image-editor-submenus-text-center': 'Center',
//   'tui-image-editor-submenus-text-right': 'Right',
//   'tui-image-editor-submenus-text-color': 'Color',
//   'tui-image-editor-submenus-text-textSize': 'Text size',
//   'tui-image-editor-submenus-mask-loadMaskImage': 'Load mask image',
//   'tui-image-editor-submenus-mask-apply': 'Apply',
//   'tui-image-editor-submenus-filter-grayscale': 'رمادي',
//   'tui-image-editor-submenus-filter-invert': 'عكس',
//   'tui-image-editor-submenus-filter-sepia': 'بني داكن',
//   'tui-image-editor-submenus-filter-sepia2': 'بني داكن 2',
//   'tui-image-editor-submenus-filter-blur': 'Blur',
//   'tui-image-editor-submenus-filter-sharpen': 'Sharpen',
//   'tui-image-editor-submenus-filter-emboss': 'Emboss',
//   'tui-image-editor-submenus-filter-removeWhite': 'Remove white',
//   'tui-image-editor-submenus-filter-removeWhite-distance': 'Distance',
//   'tui-image-editor-submenus-filter-brightness': 'Brightness',
//   'tui-image-editor-submenus-filter-noise': 'Noise',
//   'tui-image-editor-submenus-filter-pixelate': 'Pixelate',
//   'tui-image-editor-submenus-filter-colorFilter': 'Color filter',
//   'tui-image-editor-submenus-filter-colorFilter-threshold': 'Threshold',
//   'tui-image-editor-submenus-filter-tint': 'Tint',
//   'tui-image-editor-submenus-filter-multiply': 'Multiply',
//   'tui-image-editor-submenus-filter-blend': 'Blend',

//   'tui-image-editor-history-noItems': 'No history available',
//   'tui-image-editor-history-text-added': 'Added',
//   'tui-image-editor-history-text-styleChange-textAlignment-left':
//     'Align left',
//   'tui-image-editor-history-text-styleChange-textAlignment-center':
//     'Align center',
//   'tui-image-editor-history-text-styleChange-textAlignment-right':
//     'Align right',
//   'tui-image-editor-history-text-styleChange-underline': 'Underline',
//   'tui-image-editor-history-text-styleChange-underline-true':
//     'Underline',
//   'tui-image-editor-history-text-styleChange-underline-false':
//     'Not underlined',
//   'tui-image-editor-history-text-styleChange-fontStyle-normal':
//     'Not italic',
//   'tui-image-editor-history-text-styleChange-fontStyle-italic':'Italic',
//   'tui-image-editor-history-text-styleChange-fontWeight-normal':'Normal fontweight',
//   'tui-image-editor-history-text-styleChange-fontWeight-bold': 'Bold',
//   'tui-image-editor-history-text-styleChange-fontSize':'Fontsize {{0}}',
//   'tui-image-editor-history-text-fill': 'Color',
//   'tui-image-editor-history-text-general': 'Text',
//   'tui-image-editor-history-text-details': 'Moved/Resized',
//   'tui-image-editor-history-mask-general': 'Mask',
//   'tui-image-editor-history-mask-details': 'Moved/Resized',
//   'tui-image-editor-history-mask-added': 'Added',
//   'tui-image-editor-history-mask-apply': 'Applied',
//   'tui-image-editor-history-crop': 'Crop',
//   'tui-image-editor-history-flip': 'Flip',
//   'tui-image-editor-history-flip-reset': 'Reset',
//   'tui-image-editor-history-flip-flipX': 'X',
//   'tui-image-editor-history-flip-flipY': 'Y',
//   'tui-image-editor-history-rotate': 'Rotate',
//   'tui-image-editor-history-draw-general': 'Drawing',
//   'tui-image-editor-history-draw-details': 'Added/Moved/Resized',
//   'tui-image-editor-history-draw-strokeWidth': 'Width {{0}}',
//   'tui-image-editor-history-draw-stroke': 'Color',
//   'tui-image-editor-history-icon-general': 'Icon',
//   'tui-image-editor-history-icon-details': 'Added/Moved/Resized',
//   'tui-image-editor-history-icon-colorChange':'Color changed',
//   'tui-image-editor-history-icon-added': 'Added',
//   'tui-image-editor-history-icon-fill': 'Color',
//   'tui-image-editor-history-load': 'Image loaded',
//   'tui-image-editor-history-delete': 'Delete',
//   'tui-image-editor-history-delete-all': 'All',
//   'tui-image-editor-history-delete-draw': 'Drawing',
//   'tui-image-editor-history-delete-shape': 'Shape',
//   'tui-image-editor-history-delete-icon': 'Icon',
//   'tui-image-editor-history-delete-text': 'Text',
//   'tui-image-editor-history-delete-mask': 'Mask',
//   'tui-image-editor-history-shape-general': 'Shape',
//   'tui-image-editor-history-shape-details': 'Added/Moved/Resized',
//   'tui-image-editor-history-applyFilter': 'Apply filter',
//   'tui-image-editor-history-removeFilter': 'Remove filter',
//   'tui-image-editor-history-shape-strokeWidth': 'Stroke width',
//   'tui-image-editor-history-shape-stroke': 'Stroke',
//   'tui-image-editor-history-shape-fill': 'Fill',
// };
